services:
  go_test:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: database_go
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
